name: Build and push docker image
on:
  push:
    branches: [ feature/push-image ]

  workflow_dispatch:

jobs:
  docker-build:
    name: "Build and push Docker image to Github registry"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Github docker regsitry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest

      - name: Output image digest
        run: echo Docker image released ${{ steps.docker_build.outputs.digest }} with tag ${{ github.run_id }}